name: Build & Deploy

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: dotnet build
        working-directory: UniHelper
      - name: Publish
        run: dotnet publish
        working-directory: UniHelper
      - name: Copy
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          source: "./UniHelper/bin/publish/*"
          target: "/var/www/unihelper/"
