name: Build & Deploy Backend

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: dotnet build -c Release
        working-directory: UniHelper.Backend
      - name: Publish
        run: dotnet publish -c Release
        working-directory: UniHelper.Backend
      - name: Clear
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          passphrase: ${{ secrets.PASS }}
          script: rm -Rf /var/www/unihelper-backend/*
      - name: Copy
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          passphrase: ${{ secrets.PASS }}
          source: "UniHelper.Backend/bin/Release/net5.0/publish/*"
          target: "/var/www/unihelper-backend/"
      - name: Fix copy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          passphrase: ${{ secrets.PASS }}
          script: mv /var/www/unihelper-backend/UniHelper.Backend /var/www/unihelper-backend/UniHelper && cp -R /var/www/unihelper-backend/UniHelper/bin/Release/net5.0/publish/* /var/www/unihelper-backend/ && rm -Rf /var/www/unihelper-backend/UniHelper && sudo systemctl restart unihelper-backend.service
