name: Build & Deploy

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: dotnet build -c Release
        working-directory: UniHelper
      - name: Publish
        run: dotnet publish -c Release
        working-directory: UniHelper
      - name: Clear
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          passphrase: ${{ secrets.PASS }}
          script: rm -Rf /var/www/unihelper/*
      - name: Copy
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          passphrase: ${{ secrets.PASS }}
          source: "UniHelper/bin/Release/net5.0/publish/*"
          target: "/var/www/unihelper/"
      - name: Fix copy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          passphrase: ${{ secrets.PASS }}
          script: cp -R /var/www/unihelper/UniHelper/bin/Release/net5.0/publish/* /var/www/unihelper/* && rm -Rf /var/www/unihelper/UniHelper
